### PR TITLE
Updated to Angular 8

### PR DESCRIPTION
**Pull request by binoypatel**
Hi

Part of our application migration required this package to be updated to the latest version of Angular (v8), so I thought this would be a good time to have a pull request and upgrade this nice library to anuglar v8 that has latest bits from the other contributor and mine goes together when you publish this to npmjs.

Kind regards,
Binoy

### CODE REVIEW

**Comment by binoypatel** [comment]
Hi

Would it be possible to merge this or have some ETA?

Thanks,
Binoy

**Comment by MauricioFerraz** [comment]
@binoypatel and anyone interested in using this with the latest angular:

You can get away with copying the connection-service.service at https://github.com/ultrasonicsoft/ng-connection-service/blob/master/projects/connection-service/src/lib/connection-service.service.ts and just adding it to your project, taking care to add the npm packages that it requires to your package.json, like lodash.

**Comment by theCrius** [comment]
Also, you can get rid of lodash pretty easily with the latest ES syntax using Object.assign()

**Comment by binoypatel** [comment]
@theCrius Thanks for pointing out, you can get the updated version from [https://github.com/binoypatel/ng-connection-service](url)

Thanks,
Binoy

**Comment by MauricioFerraz** [comment]
@binoypatel the address that link is pointing to is different from the displayed text.

**Pull request closed without merging**
